#:schema https://raw.githubusercontent.com/yunanwg/brilliant-CV/main/metadata.toml.schema.json

# Set the output language
# INFO: value must matches folder suffix; i.e "zh" -> "./modules_zh"
language = "en"

[layout]
    # Optional values: skyblue, red, nephritis, concrete, darknight
    # You can also use a custom color by hex code i.e. "#1E90FF"
    awesome_color = "#0070f2"

    # Skips are for controlling the spacing between sections and entries
    before_section_skip = "1pt"
    before_entry_skip = "1pt"
    before_entry_description_skip = "1pt"

    # Optional: sets paper size and margins. Possible values: a4 (default), us-letter
    paper_size = "a4"

    [layout.fonts]
        regular_fonts = ["Source Sans 3"]
        header_font = "Roboto"

    [layout.header]
        # Optional values: left, center, right
        header_align = "left"

        # Decide if you want to display profile photo or not
        display_profile_photo = false
        # Radius in % to clip profile photo at
        profile_photo_radius = "50%"
        info_font_size = "10pt"

    [layout.entry]
        # Decide if you want to put your company in bold or your position in bold
        display_entry_society_first = true

        # Decide if you want to display organisation logo or not
        display_logo = false

    [layout.footer]
        # Decide if you want to display page counter or not
        display_page_counter = false

        # Decide if you want to display the footer or not
        display_footer = true


[inject]
    # Decide if you want to inject AI prompt or not
    inject_ai_prompt = false

    # Decide if you want to inject keywords or not
    inject_keywords = true
    injected_keywords_list = ["Software Engineering", "Next.js", "TypeScript", "Java", "Python", "SAP"]

[personal]
    first_name = "Max"
    last_name = "Meinel"

    # The order of this section will affect how the entries are displayed
    [personal.info]
        email = "max.meinel@sap.com"
        phone = "+49 XXX XXXXXXX"
        linkedin = "max-meinel"
        github = "max-meinel"
        homepage = "max-meinel.de"
        location = "Mannheim, Germany"

[lang.de]
    header_quote = "Dualer Student Wirtschaftsinformatik (Software Engineering) bei SAP & DHBW Mannheim"
    cv_footer = "Lebenslauf"
    letter_footer = "Anschreiben"

[lang.en]
    header_quote = "Dual Student Business Informatics (Software Engineering) at SAP & DHBW Mannheim"
    cv_footer = "Curriculum vitae"
    letter_footer = "Cover letter"
